theme: minima
title: Andrew Ruhnow | Data Analytics Portfolio
author: Andrew Ruhnow
description: Showcasing data-driven projects in Excel, Python, SQL, and Tableau — turning complex data into actionable insights.

# Navigation menu
header_pages:
  - index.md
  - projects.md
  - about.md
  - contact.md
